apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  generation: 1
  labels:
    strimzi.io/cluster: strimzi-cluster
  name: TOPIC-NAME
  namespace: zen
spec:
  config:
    retention.ms: 1800000
    segment.bytes: 1073741824
  partitions: 1
  replicas: 1
  topicName: TOPIC-NAME
