apiVersion: probes.integrations.noi.ibm.com/v1beta1
kind: PrometheusProbe
metadata:
  name: example-prometheusprobe
  namespace: noi
  labels:
    app.kubernetes.io/instance: example-prometheusprob
    app.kubernetes.io/managed-by: netcool-integrations-operator
    app.kubernetes.io/name: prometheusprobe
spec:
  helmValues:
    arch: amd64
    global:
      image:
        secretName: cp.stg.icr.io
        useTag: false
      serviceAccountName: ''
    image:
      digest: 'sha256:db93b631dde5f724e0234842f56235893f1697e351e3f7e8b1e044905cbdcd07'
      pullPolicy: Always
      repository: cp.icr.io/cp/noi-int/netcool-probe-messagebus
      tag: 13.2.0-amd64
      testImageDigest: 'sha256:af9b0cf8ade76f2c32f48c54ce6ad8ad9e10a76f8af3940b5a18ff24b419f28c'
      testImageTag: 3.4.0-amd64
      testRepository: cp.icr.io/cp/noi-int/netcool-integration-util
    netcool:
      backupHost: demo-noi-objserv-agg-backup.noi.svc.cluster.local
      backupPort: '4100'
      backupServer: AGG_B
      connectionMode: default
      primaryHost: demo-noi-objserv-agg-primary.noi.svc.cluster.local
      primaryPort: 4100
      primaryServer: AGG_P
      secretName: ''
    probe:
      locale: en_US.utf8
      messageLevel: warn
      setUIDandGID: true
      sslServerCommonName: ''
    prometheusProbe:
      autoscaling:
        cpuUtil: 60
        enabled: true
        maxReplicas: 3
        minReplicas: 1
      enabled: true
      ingress:
        enabled: false
        host: ''
        tlsEnabled: false
      poddisruptionbudget:
        enabled: false
        minAvailable: 1
      replicaCount: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
  license:
    accept: true
  version: 4.6.0
